services:
  redis_storage:
    image: redis:7.4-alpine
    container_name: chatting_container_redis
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $REDIS_PUBLIC_PORT:$REDIS_CONTAINER_PORT
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - chatting_network

  rabbit_mq:
    image: rabbitmq:4.0.6-management-alpine
    container_name: chatting_container_rabbitmq
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $RABBIT_MQ_PUBLIC_PORT:$RABBIT_MQ_CONTAINER_PORT
      - $RABBIT_MQ_MANAGEMENT_PUBLIC_PORT:$RABBIT_MQ_MANAGEMENT_CONTAINER_PORT
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - chatting_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'
    networks:
      - chatting_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - chatting_network

networks:
  chatting_network:
    driver: bridge
